
scoped_ptr : scoped_ptr.o
	g++ -o scoped_ptr scoped_ptr.cpp ../common/std.hpp

scoped_array : scoped_array.o
	g++ -o scoped_array scoped_array.cpp ../common/std.hpp

shared_ptr1 : shared_ptr1.o
	g++ -o shared_ptr1 -g shared_ptr1.cpp ../common/std.hpp

clean:
	rm -rf scoped_ptr scoped_ptr.o scoped_array scoped_array.o shared_ptr1 shared_ptr1.o